### ISSUE TITLE
"veintiún" causes exception 

### ISSUE THREAD

**Issue by alvaro777** [cartovarc/spa2num#9]
Hi there,
First of all, thank you so much for the library! It was hard to find a library that does this already :)
I noticed that when we use the word "veintiún" (with a graphical accent), the library returns an exception even though it is correct: https://dle.rae.es/veinti%C3%BAn
![image](https://user-images.githubusercontent.com/9385752/106527968-a2e57a80-64ad-11eb-8d4a-5196359757c3.png)
Regards,
Alvaro

**Comment by alvaro777** [comment]
I think the fix is to add:
|ún
to line 107 in converter.py
![image](https://user-images.githubusercontent.com/9385752/106529475-2607d000-64b0-11eb-867e-d0172e9509d6.png)

**Comment by cartovarc** [comment]
Hi! I make a commit fixing that issue on a new release 0.0.6, please tell me if you have another problem :baby_chick:

**Comment by alvaro777** [comment]
Awesome! that was lightning fast!
For sure, I'll let you know if find anything else
